import path from 'node:path';
import { defineConfig } from 'vitest/config';
import react, { reactCompilerPreset } from '@vitejs/plugin-react';
import babel from '@rolldown/plugin-babel';
import tailwindcss from '@tailwindcss/vite';
import { tanstackRouter } from '@tanstack/router-plugin/vite';
import { loadEnv } from 'vite';
import { compression } from 'vite-plugin-compression2';

export default defineConfig(({ mode }) => {
  // Load env file based on `mode` in the current working directory.
  // Set the third parameter to '' to load all envs regardless of prefix.
  const env = loadEnv(mode, process.cwd(), '');

  return {
    base: env.VITE_BASE_URL || '/',
    // Vite plugins are executed in the order they are defined. The order here is important:
    plugins: [
      tanstackRouter(), // must run before react() to generate routeTree.gen.ts
      react(), // JSX transform (React 19's new transform)
      babel({ presets: [reactCompilerPreset()] }), // React Compiler — must run after react()
      tailwindcss(), // CSS processing — order-independent but convention is last
      compression({ algorithms: ['brotliCompress'], exclude: [/\.(br)$/, /\.(gz)$/] }),
    ],
    build: {
      chunkSizeWarningLimit: 1000, // no chunk splitting (Edge clears cache on close); warn if bundle grows unexpectedly beyond current ~850 kB
      rollupOptions: {
        input: {
          main: path.resolve(__dirname, 'index.html'),
          // Spring Boot serves this page to unauthenticated users instead of the SPA.
          // Processed by Vite so %VITE_*% env vars are available (e.g. app title, branding).
          welcome: path.resolve(__dirname, 'welcome/index.html'),
        },
      },
    },
    server: {
      port: 3000,
      proxy: {
        '/api': {
          target: 'http://localhost:8080',
          changeOrigin: true,
        },
        // Admin channel (Account management); same origin so the session and CSRF cookies apply.
        '/admin/api': {
          target: 'http://localhost:8080',
          changeOrigin: true,
        },
        '/login': {
          target: 'http://localhost:8080',
          changeOrigin: true,
        },
        '/logout': {
          target: 'http://localhost:8080',
          changeOrigin: true,
        },
      },
    },
    resolve: {
      // Path aliases for cleaner imports (remember to update tsconfig.json & tsconfig.app.json paths accordingly)
      alias: {
        '@': path.resolve(__dirname, './src'),
        '@assets': path.resolve(__dirname, './src/assets'),
        '@components': path.resolve(__dirname, './src/components'),
        '@features': path.resolve(__dirname, './src/features'),
        '@lib': path.resolve(__dirname, './src/lib'),
        '@hooks': path.resolve(__dirname, './src/hooks'),
        '@ui': path.resolve(__dirname, './src/components/ui'),
      },
    },
    test: {
      globals: true,
      environment: 'jsdom',
      setupFiles: ['./src/test/setup.ts'],
      exclude: [
        '**/node_modules/**', // dependencies (node_modules) comes with their own tests and shouldn't be run by Vitest
        '**/e2e/**', // e2e tests use another framework (Playwright/Cypress/Selenium) and shouldn't be run by Vitest
        'src/**/*.stories.{ts,tsx}',
      ],
      coverage: {
        provider: 'v8',
        include: ['src/**/*.{ts,tsx}'],
        reporter: ['text', 'html', 'json-summary', 'lcov'],
        exclude: [
          // Test files themselves shouldn't count toward coverage
          'src/**/*.test.{ts,tsx}', // common test file naming convention
          'src/**/*.spec.{ts,tsx}', // alternative common test file naming convention
          '**/__tests__/**', // common test directory convention

          // Common patterns to exclude from coverage as they contain boilerplate or non-critical code
          '**/*.d.ts', // type declaration files have no runtime code
          'src/main.tsx', // app entry point — just wires up React root, nothing to unit test
          'src/routeTree.gen.ts', // auto-generated by TanStack Router plugin — never edit or test directly
          'src/**/*.stories.{ts,tsx}', // Storybook story files — UI demos, not runtime logic
          'src/components/ui/**', // shadcn/Base UI primitives — third-party-sourced boilerplate
          'src/api/generated/**', // orval-generated files — not hand-written code
          'src/routes/**', // route files are wiring (createFileRoute, loaders) — logic lives in components/queries
          'src/test/**', // test infrastructure
          'src/lib/constants.ts', // plain value exports — no logic to test
        ],
      },
    },
  };
});
