-- Accounts gain an email, a role, an enabled flag, lockout bookkeeping and a creation time, and
-- password reset tokens get their table. Portable SQL only: no H2-only syntax in versioned
-- migrations (the dev/test seed under db/seed may use H2's MERGE).

-- Usernames are stored lowercase from now on, so lookups can be case-insensitive on a plain
-- unique index. Two existing names that differ only in case would fail the unique constraint here.
UPDATE user_account SET username = LOWER(username);

ALTER TABLE user_account ADD COLUMN email VARCHAR(254);
-- Before this feature only the dev/test seed created accounts. Any other row has no email to
-- backfill and fails the NOT NULL below, which stops the migration instead of inventing one.
UPDATE user_account SET email = 'johndoe@example.com' WHERE username = 'johndoe';
ALTER TABLE user_account ALTER COLUMN email SET NOT NULL;
ALTER TABLE user_account ADD CONSTRAINT uk_user_account_email UNIQUE (email);

ALTER TABLE user_account ADD COLUMN role VARCHAR(10) DEFAULT 'USER' NOT NULL;
ALTER TABLE user_account ADD CONSTRAINT ck_user_account_role CHECK (role IN ('USER', 'ADMIN'));

ALTER TABLE user_account ADD COLUMN enabled BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE user_account ADD COLUMN failed_login_attempts INT DEFAULT 0 NOT NULL;
ALTER TABLE user_account ADD COLUMN locked_until TIMESTAMP WITH TIME ZONE;
-- The default backfills existing rows with the migration time.
ALTER TABLE user_account
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

-- Only the SHA-256 hex of a reset token is stored. Deleting an account removes its tokens.
CREATE TABLE password_reset_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    token_hash CHAR(64)                 NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_token_user
        FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE
);
CREATE INDEX ix_password_reset_token_user ON password_reset_token (user_id);
