/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export type CreateAccountRequestRole = (typeof CreateAccountRequestRole)[keyof typeof CreateAccountRequestRole];

export const CreateAccountRequestRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export interface CreateAccountRequest {
  /**
   * @minLength 0
   * @maxLength 100
   */
  username: string;
  role: CreateAccountRequestRole;
}

export type CreatedAccountResponseRole = (typeof CreatedAccountResponseRole)[keyof typeof CreatedAccountResponseRole];

export const CreatedAccountResponseRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export interface CreatedAccountResponse {
  username: string;
  role: CreatedAccountResponseRole;
  /** Shown once; hand it to the account holder. It cannot be retrieved later. */
  temporaryPassword: string;
  temporaryPasswordExpiresAt: string;
}

export type AccountSummaryResponseRole = (typeof AccountSummaryResponseRole)[keyof typeof AccountSummaryResponseRole];

export const AccountSummaryResponseRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export interface AccountSummaryResponse {
  id: string;
  username: string;
  role: AccountSummaryResponseRole;
  enabled: boolean;
  createdAt: string;
}

export type ChangeAccountRoleRequestRole =
  (typeof ChangeAccountRoleRequestRole)[keyof typeof ChangeAccountRoleRequestRole];

export const ChangeAccountRoleRequestRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;

export interface ChangeAccountRoleRequest {
  role: ChangeAccountRoleRequestRole;
}

export interface SetAccountEnabledRequest {
  enabled: boolean;
}
