package com.example.helloauth;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.StringWriter;
import java.nio.file.Path;
import liquibase.Contexts;
import liquibase.LabelExpression;
import liquibase.Liquibase;
import liquibase.database.DatabaseFactory;
import liquibase.database.OfflineConnection;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

/** SQL generation checks supplement, but do not replace, the opt-in live vendor test. */
class DatabaseMigrationSqlTests {
    @TempDir
    Path directory;

    @ParameterizedTest
    @CsvSource({"mysql, DATETIME(6), BLOB, AUTO_INCREMENT", "postgresql, TIMESTAMP(6) WITH TIME ZONE, BYTEA, GENERATED BY DEFAULT AS IDENTITY"})
    void generatesVendorSpecificSchema(String vendor, String instantType, String binaryType,
            String identity) throws Exception {
        try (var resources = new ClassLoaderResourceAccessor()) {
            var connection = new OfflineConnection("offline:" + vendor + "?version="
                + (vendor.equals("mysql") ? "8.4" : "17") + "&changeLogFile="
                + directory.resolve(vendor + ".csv").toString().replace('\\', '/'), resources);
            var database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(connection);
            try (var liquibase = new Liquibase("db/changelog/db.changelog-master.yaml", resources, database)) {
                var sql = new StringWriter();
                liquibase.update(new Contexts(), new LabelExpression(), sql);
                assertThat(sql.toString().toUpperCase())
                    .contains(instantType, binaryType, identity, "SPRING_SESSION_ATTRIBUTES",
                        "VARCHAR(255)", "FK_RESET_TOKEN_USER", "ON DELETE CASCADE")
                    .doesNotContain("${INSTANTTYPE}", "DROP TABLE");
            }
        }
    }
}
