package com.sgtechstack.helloauth.audit;

public enum AuditEvent {

	USER_REGISTERED,
	LOGIN_SUCCEEDED,
	LOGIN_FAILED,
	LOGIN_THROTTLED,
	ACCOUNT_LOCKED,
	LOGOUT,
	PASSWORD_RESET_REQUESTED,
	PASSWORD_RESET_THROTTLED,
	PASSWORD_RESET_COMPLETED,
	PASSWORD_RESET_REJECTED,
	USER_ENABLED,
	USER_DISABLED,
	USER_ROLE_CHANGED,
	USER_DELETED,
	ADMIN_ACTION_REJECTED,
	ADMIN_BOOTSTRAPPED

}
