/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import type { ChangeAccountRoleRequest, SetAccountEnabledRequest } from '../openAPIDefinition.schemas';

import { orvalFetch } from '../../../lib/openapi-orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type changeRoleResponse204 = {
  data: void;
  status: 204;
};

export type changeRoleResponseSuccess = changeRoleResponse204 & {
  headers: Headers;
};
export type changeRoleResponse = changeRoleResponseSuccess;

export const getChangeRoleUrl = (id: string) => {
  return `/admin/api/users/${id}/role`;
};

export const changeRole = async (
  id: string,
  changeAccountRoleRequest: ChangeAccountRoleRequest,
  options?: Parameters<typeof orvalFetch>[1],
): Promise<changeRoleResponse> => {
  const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return orvalFetch<changeRoleResponse>(getChangeRoleUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changeAccountRoleRequest),
  });
};

export const getChangeRoleMutationKey = () => ['changeRole'] as const;

export const getChangeRoleMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof changeRole>>, TError, ChangeRoleMutationVariables, TContext>;
  request?: SecondParameter<typeof orvalFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof changeRole>>, TError, ChangeRoleMutationVariables, TContext> => {
  const mutationKey = getChangeRoleMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeRole>>, ChangeRoleMutationVariables> = (props) => {
    const { id, data } = props ?? {};

    return changeRole(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeRoleMutationResult = NonNullable<Awaited<ReturnType<typeof changeRole>>>;
export type ChangeRoleMutationBody = ChangeAccountRoleRequest;
export type ChangeRoleMutationError = unknown;
export type ChangeRoleMutationVariables = { id: string; data: ChangeAccountRoleRequest };

export const useChangeRole = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeRole>>,
      TError,
      ChangeRoleMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof orvalFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof changeRole>>, TError, ChangeRoleMutationVariables, TContext> => {
  return useMutation(getChangeRoleMutationOptions(options), queryClient);
};
export type setEnabledResponse204 = {
  data: void;
  status: 204;
};

export type setEnabledResponseSuccess = setEnabledResponse204 & {
  headers: Headers;
};
export type setEnabledResponse = setEnabledResponseSuccess;

export const getSetEnabledUrl = (id: string) => {
  return `/admin/api/users/${id}/enabled`;
};

export const setEnabled = async (
  id: string,
  setAccountEnabledRequest: SetAccountEnabledRequest,
  options?: Parameters<typeof orvalFetch>[1],
): Promise<setEnabledResponse> => {
  const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return orvalFetch<setEnabledResponse>(getSetEnabledUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setAccountEnabledRequest),
  });
};

export const getSetEnabledMutationKey = () => ['setEnabled'] as const;

export const getSetEnabledMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof setEnabled>>, TError, SetEnabledMutationVariables, TContext>;
  request?: SecondParameter<typeof orvalFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof setEnabled>>, TError, SetEnabledMutationVariables, TContext> => {
  const mutationKey = getSetEnabledMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof setEnabled>>, SetEnabledMutationVariables> = (props) => {
    const { id, data } = props ?? {};

    return setEnabled(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetEnabledMutationResult = NonNullable<Awaited<ReturnType<typeof setEnabled>>>;
export type SetEnabledMutationBody = SetAccountEnabledRequest;
export type SetEnabledMutationError = unknown;
export type SetEnabledMutationVariables = { id: string; data: SetAccountEnabledRequest };

export const useSetEnabled = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setEnabled>>,
      TError,
      SetEnabledMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof orvalFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof setEnabled>>, TError, SetEnabledMutationVariables, TContext> => {
  return useMutation(getSetEnabledMutationOptions(options), queryClient);
};
export type _deleteResponse204 = {
  data: void;
  status: 204;
};

export type _deleteResponseSuccess = _deleteResponse204 & {
  headers: Headers;
};
export type _deleteResponse = _deleteResponseSuccess;

export const getDeleteUrl = (id: string) => {
  return `/admin/api/users/${id}`;
};

export const _delete = async (id: string, options?: Parameters<typeof orvalFetch>[1]): Promise<_deleteResponse> => {
  return orvalFetch<_deleteResponse>(getDeleteUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteMutationKey = () => ['_delete'] as const;

export const getDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError, _DeleteMutationVariables, TContext>;
  request?: SecondParameter<typeof orvalFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError, _DeleteMutationVariables, TContext> => {
  const mutationKey = getDeleteMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof _delete>>, _DeleteMutationVariables> = (props) => {
    const { id } = props ?? {};

    return _delete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>;

export type _DeleteMutationError = unknown;
export type _DeleteMutationVariables = { id: string };

export const useDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError, _DeleteMutationVariables, TContext>;
    request?: SecondParameter<typeof orvalFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof _delete>>, TError, _DeleteMutationVariables, TContext> => {
  return useMutation(getDeleteMutationOptions(options), queryClient);
};
